lang: ruby
rvm: 2.5
env:
  global:
  - CGO_ENABLED: 1

before_install:
- if [[ "$TRAVIS_OS_NAME" == 'linux' ]]; then bash ./.travis/install-linux.sh ; fi

install:
- eval "$(gimme 1.10)"
- go env
- go get github.com/gz-c/gox

before_script:
- make -C gopath/src/github.com/skycoin/libskycoin dep

script:
- "./.travis/skyapi.sh"
- make build

before_deploy:
- make package

deploy:
  - provider: releases
    file:
    - "./lib/skyapi/skyapi-$(echo ${TRAVIS_TAG} | cut -d'v' -f 2).gem"
    - "./lib/skycoin/skycoin-$(echo ${TRAVIS_TAG} | cut -d'v' -f 2).gem"
    skip_cleanup: true
    on:
      tags: true
      repo: simelo/libskycoin-ruby
    api_key:
      secure: lTRL5zL+cHNjZot/xFOhzA6eEaFADZPTuUWyWEhDhzFOJWNTIt3p/o25pf0NSfgIkQQv+sLtYWS305UBAHhUbmfx+b1ilAHktfOl7ehykob3vUB3RC79f3xiX/ry9SJ7GN4DHqffz0vU+lZ0oq11KUDrxi/wQWarY/oapOGyiTpxp79PxmEkfHCLOkgXChBiGbLJwdFMs6Npf1ma6SYDL7+/mlpVWFzNVus3b+FB1Otr2SAFRSxQ21ma+YP1gT/qy0sEcmIZYj3qoMZgOViGObQeWWCZLveevkIG1O5QX1cF77IfDmkhRJewJhtvnA/Z7YL30XOzp7SghdiP/XxvBMlh8Ex0QJCrl65vqAWoHgNP/d9DAJz6n20RdpsrK4olXpFWWNYaLcaTJKmRR2uLCRlief308Q+0f3acaAT27TiQ8ZotKXxx1Bx5mj2j21yZo3zfccXv2e1k7ibOmPpNC8USnuQ0Hr4PpeMPjp8o8aRsJA9C14UgrTCgFlpvDV8pSk0w8Zxf2jJMQsO42RKg+RKFe8uqHrqaWFbpFmSpd9wudZDNWbvdUoPqAumRrujCGvht023RbYE/KRcA/I949tak/poQvDfm1g3gYQ8DOBTTYCU+sylOuo1OLOBGdRq9gByKOteMMrkyqkV+brVaPl7lFHEFID8k2KP8aWMtBDY=

  - provider: script
    script: bash .travis/deploy_rubygems.sh
    skip_cleanup: true
    on:
      tags: true

notifications:
  email: false
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
